apiVersion: v1
kind: Service
metadata:
  name: k8s-kafka-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: k8s-kafka

  ports:
    - name: http
      port: 2181
      nodePort: 32181
      
    - name: tcp
      port: 9092
      nodePort: 32182
  type: NodePort
