apiVersion: v1
kind: Pod
metadata:
  name: hello-world-app-secret-pod
  labels:
    app: hello-world-app-secret
spec:
  containers:
  - name: hello-world-webapp-secret
    image: nikbhi15docker/k8s-springboot-helloworld-secret-app:v1.0
    imagePullPolicy: Always
    env:
        # Define the environment variable
        - name: SECRETS_CRED_USER_NAME
          valueFrom:
            secretKeyRef:
              # The ConfigMap containing the value you want to assign to SECRETS_CRED_USER_NAME
              name: secret-env-credentials
              # Specify the key associated with the value
              key: secret.credentials.user.name              
        - name: SECRETS_CRED_USER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              # The ConfigMap containing the value you want to assign to SECRETS_CRED_USER_ACCESS_TOKEN
              name: secret-env-credentials
              # Specify the key associated with the value
              key: secret.credentials.access.token      
    volumeMounts:
    - name: spring-boot-app-env-secret-volume
      mountPath: "/config"
  volumes:
    - name: spring-boot-app-env-secret-volume
      secret:
        secretName: secret-file-credentials
        items:
        - key: application.properties
          path: application.properties
  restartPolicy: Always  
  