apiVersion: v1
kind: Service
metadata:
  name: sparkintegratortest-webapp-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: my-webapp

  ports:
    - name: http
      port: 8082
      nodePort: 30020

  type: NodePort
