apiVersion: v1
kind: Service
metadata:
  name: hello-world-autoscaling-webapp-v1-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: hello-world-webapp-autoscaling-v1

  ports:
    - name: http
      port: 8080
      nodePort: 31682

  type: NodePort

  